# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: FtpUpload@2
  inputs:
        credentialsOption: 'inputs'
        serverUrl: 'ftp://156.67.222.68'
        username: 'u839111123'
        password: 'C#F=d8mO~BpFv96'
        rootDirectory: '$(Build.ArtifactStagingDirectory)'
        filePatterns: |
          *.exe
          *.dll
        remoteDirectory: '/public_html/cdn/products/win-netmeter/ci/$(Build.BuildId)/'
        clean: true
        preservePaths: false
        trustSSL: false
        
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'WinTenDev.WinNetMeter'
